### ISSUE TITLE
Thank you for the Blogger theme

### ISSUE THREAD

**Issue by DealsBeam** [alifprihantoro/pawartatech#8]
Thank you for creating this awesome Blogger theme, it would be wonderful if you are able to optimize for performance https://pagespeed.web.dev/analysis/https-pawartatech-blogspot-com/gf3r7so05c?use_original_url=true&form_factor=mobile (check mobile and desktop performance level)

**Comment by alifprihantoro** [comment]
Thank you for your valuable feedback. We appreciate your suggestions and are committed to optimizing the loading times and responsiveness of our Blogger template. 

As the template is still in development, we will continue to make updates to ensure it becomes stable and provides a smooth user experience across all devices. Your input is crucial in helping us achieve this goal. Stay tuned for future updates, and thank you for your support!

**Comment by aliefprihantoro** [comment]
The performance issues have been improved, and several bugs have been fixed. Please check the latest version [here](https://github.com/alifprihantoro/pawartatech/releases/tag/v1.3.0) to see the improvements. Or see the pages speed [here](https://pagespeed.web.dev/analysis/https-pawartatech-blogspot-com/2oq778pfkp?form_factor=mobile).
